CREATE OR REPLACE PROCEDURE INSERT_EMPLOYEE(
    FIRSTNAME IN VARCHAR2,
    LASTNAME IN VARCHAR2,
    TITLEID IN NUMBER,
    EMAIL IN VARCHAR2,
    PW IN VARCHAR2)
AS
BEGIN
    INSERT INTO EMPLOYEES VALUES( EMPID_SEQ.NEXTVAL, FIRSTNAME, LASTNAME, TITLEID, EMAIL, PW, DEFAULT);
END;
/
