CREATE OR REPLACE PROCEDURE INSERT_REQUEST(
    EMPID NUMBER,
    AMMOUNT NUMBER,
    REQUESTDESC VARCHAR2)
AS
BEGIN
    INSERT INTO OPENREQUESTS VALUES(REQUESTID_SEQ.NEXTVAL, EMPID, DEFAULT, AMMOUNT, REQUESTDESC, TO_CHAR(SYSTIMESTAMP), (NULL), (NULL), (NULL));
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE FINALIZE_REQUEST(
    UREQUESTID NUMBER,
    STATUS VARCHAR2,
    NOTES VARCHAR2,
    MANAGERID NUMBER)
AS
    EMPID_C NUMBER(10);
    AMMOUNT_C NUMBER(10,2);
    REQUESTDESC_C VARCHAR2(150);
    OPENDATE_C VARCHAR2(150);
    
BEGIN
    SELECT EMPID, AMMOUT, REQUESTDESC, OPENDATE
    INTO  EMPID_C, AMMOUNT_C, REQUESTDESC_C, OPENDATE_C
    FROM OPENREQUESTS
    WHERE REQUESTID=UREQUESTID;
    
    INSERT INTO CLOSEDREQUESTS
        VALUES(UREQUESTID, EMPID_C, STATUS, AMMOUNT_C, REQUESTDESC_C, OPENDATE_C, TO_CHAR(SYSTIMESTAMP), NOTES, MANAGERID);
    DELETE FROM OPENREQUESTS
        WHERE REQUESTID=UREQUESTID;
    COMMIT;
END;
/